openapi: 3.0.1
info:
  title: Star Wars
  description: Implementing the Star Wars API.
  version: '1.0'
servers:
  - url: http://apim-integrations-wkshp-mxc-001.azure-api.net/sw
paths:
  /people/:
    get:
      summary: Get People
      description: GET People
      operationId: get-people
      responses:
        '200':
          description: ''
  '/people/{id}/':
    get:
      summary: Get People By Id
      description: GET People by ID
      operationId: get-people-by-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]